### ISSUE TITLE
Create a landing page with all previous editions

### ISSUE THREAD

**Issue by Palid** [hackerspace-silesia/HackSilesia#15]
As in title.

**Comment by galuszkak** [comment]
Do you want different subdomains for every edition? for ex. 2014.hacksilesia.pl /cc @Palid

**Comment by Palid** [comment]
Repositories for subdomains are prepared @galuszkak, now we just need DNS update and previous editions links in the new edition page.

New repos: 
https://github.com/hackerspace-silesia/hacksilesia-2016
https://github.com/hackerspace-silesia/hacksilesia-2014/

**Comment by Palid** [comment]
I guess it's partly done? Now we just need a landing page for that, but let's leave it as it is for now.
